[tool.poetry]
name = "module-1-scapy"
version = "0.1.0"
description = "Module de sécurité Python - IDS/IPS avec Scapy, analyse de shellcode et automatisation d'attaques web"
authors = ["Marceau KAKOU | Gabriel PIVATY"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
scapy = "^2.5.0"
pylibemu = "^0.6.1"
matplotlib = "^3.7.1"
tabulate = "^0.9.0"
colorama = "^0.4.6"
requests = "^2.30.0"
pillow = "^10.0.0"
pytesseract = "^0.3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pylint = "^2.17.4"
pytest-cov = "^4.1.0"
black = "^23.3.0"
pre-commit = "^3.3.1"

[tool.poetry.scripts]
ids = "src.module_1_scapy.main:main"
analyze-shellcode = "src.module_2_shellcode.main:main"
webattack = "src.module_3_web.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.pylint.messages_control]
disable = ["C0111", "C0103", "C0303", "W1201", "C0330", "C0326", "W0511"]
